# Generated by Django 3.0.5 on 2020-04-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employtment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employtment_name', models.CharField(max_length=150, verbose_name='Nome da Vaga')),
                ('slug', models.SlugField(verbose_name='Palavra chave')),
                ('requirements', models.CharField(max_length=150, verbose_name='Nome da Vaga')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salário')),
                ('jobs_vacancy', models.IntegerField(verbose_name='Quantidade de Vagas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['employtment_name'],
            },
        ),
        migrations.CreateModel(
            name='Apply_for',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate', verbose_name='Candidato')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employtment', verbose_name='Vaga')),
            ],
        ),
    ]
