# Generated by Django 3.0.5 on 2020-04-16 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200416_1710'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply_for',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AddField(
            model_name='apply_for',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply_for',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='apply_for',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_for', to='accounts.Candidate', verbose_name='Candidato'),
        ),
        migrations.AlterField(
            model_name='apply_for',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_for', to='core.Employtment', verbose_name='Vaga'),
        ),
        migrations.AlterField(
            model_name='employtment',
            name='requirements',
            field=models.TextField(verbose_name='Requisitos'),
        ),
        migrations.AlterUniqueTogether(
            name='apply_for',
            unique_together={('candidate', 'job')},
        ),
    ]
