# Generated by Django 3.0.5 on 2020-04-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200417_1716'),
        ('core', '0002_auto_20200416_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum_Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_file', models.FileField(default='', upload_to='', verbose_name='Curriculo')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_candidate', to='accounts.Candidate', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Curriculo',
                'verbose_name_plural': 'Curriculos',
            },
        ),
    ]
