# Generated by Django 3.0.5 on 2020-04-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_curriculum_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curriculum_Candidate',
        ),
    ]
