# Generated by Django 3.0.5 on 2020-04-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User')),
                ('cnpj', models.CharField(max_length=11, verbose_name='CNPJ')),
                ('whatsapp', models.CharField(max_length=12, verbose_name='WhatsApp')),
                ('responsibly', models.CharField(max_length=150, verbose_name='Responsável')),
            ],
        ),
    ]
