# Generated by Django 3.0.5 on 2020-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200417_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum',
            field=models.FileField(upload_to='midia/curriculum', verbose_name='Curriculo'),
        ),
    ]
