# Generated by Django 3.0.5 on 2020-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200417_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum',
            field=models.FileField(upload_to='static/<django.db.models.fields.related.OneToOneField>/curriculum', verbose_name='Curriculo'),
        ),
    ]
