# Generated by Django 3.0.5 on 2020-04-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200418_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum',
            field=models.FileField(upload_to='static/candidate/curriculum', verbose_name='Curriculo'),
        ),
    ]
